apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.1.0
          ports:
            - name: db
              protocol: TCP
              containerPort: 3306
          volumeMounts:
            - mountPath: '/var/lib/mysql'
              name: mysql-volume
            - mountPath: '/docker-entrypoint-initdb.d'
              name: mysql-configmap-volume
          envFrom:
            - secretRef:
                name: mysql-secret
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-configmap-volume
          configMap:
            name: mysql-configmap