apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: connection
      protocol: TCP
      port: 27017
      targetPort: 27017
